# Generated by Django 5.0.1 on 2024-01-22 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
    ]
