# Generated by Django 5.0.1 on 2024-01-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0002_alter_forumtopic_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
