# Generated by Django 5.0.1 on 2024-01-22 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0003_alter_forumtopic_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 22, 19, 21, 15, 719765, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
