# Generated by Django 5.0.1 on 2024-01-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_normal_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Moderator'), (2, 'Normal User')], default=2),
        ),
    ]
