# Generated by Django 5.0.1 on 2024-01-22 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleRoutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('route_title', models.CharField(blank=True, max_length=300, null=True)),
                ('route', models.SlugField(blank=True, max_length=100, null=True)),
                ('user_type', models.SmallIntegerField()),
            ],
        ),
    ]
