# Generated by Django 5.0.1 on 2024-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_customuser_ban_end_date_customuser_ban_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ban_end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ban_start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
